apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgurl-core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pgurl-core
    spec:
      containers:
        - name: pgurl-core
          image: herber523/pgurl-core
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pgurl-core-service
  labels:
    name: pgurl-core-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: pgurl-core
  type: NodePort


